### ISSUE TITLE
Add the content guide toolkit meta info

### ISSUE THREAD

**Issue by maya** [skylight-hq/skylight.digital#158]
- [x] tagline for the guide
   - A guide on how to write clear, accessible, and user-friendly content at Skylight
- [x] descriptions for each page (for SEO and social link shares)
- [x] tags for the guide
  - content, guide
