### ISSUE TITLE
Create the service design toolkit meta info

### ISSUE THREAD

**Issue by maya** [skylight-hq/skylight.digital#159]
- [ ] A one-sentence tagline for the guide
- [ ] descriptions for each page (for SEO and social link shares)
- [ ] tags for the guide
  - service design, guide
